tmux new -d -s t0_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=0 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t1_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=1 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t2_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=2 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t3_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=3 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t4_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=4 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t5_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=5 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t6_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=6 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t7_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=7 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t8_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=8 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t9_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=9 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t10_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=10 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t11_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=11 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t12_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=12 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t13_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=13 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t14_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=14 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t15_0 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=15 --node=4 --gpu=7 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'


tmux new -d -s t0_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=0 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t1_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=1 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t2_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=2 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t3_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=3 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t4_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=4 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t5_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=5 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t6_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=6 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t7_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=7 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t8_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=8 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t9_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=9 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t10_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=10 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t11_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=11 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t12_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=12 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t13_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=13 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t14_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=14 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t15_1 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=15 --node=5 --gpu=1 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'


tmux new -d -s t0_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=0 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t1_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=1 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t2_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=2 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t3_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=3 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t4_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=4 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t5_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=5 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t6_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=6 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t7_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=7 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t8_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=8 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t9_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=9 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t10_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=10 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t11_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=11 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t12_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=12 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t13_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=13 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t14_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=14 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t15_2 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=15 --node=6 --gpu=2 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'


tmux new -d -s t0_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=0 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t1_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=1 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t2_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=2 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t3_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=3 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t4_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=4 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t5_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=5 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t6_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=6 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t7_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=7 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t8_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=8 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t9_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=9 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t10_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=10 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t11_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=11 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t12_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=12 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t13_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=13 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t14_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=14 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'
tmux new -d -s t15_3 'export PYTHONPATH=util/;python3 train_anshu.py --repetition=15 --node=7 --gpu=3 --gpu_usage=0.05 --load_epoch=15 --n_epochs=5'

